version: "3" # composeファイルのバージョン
services:
  backend:
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
    tty: true # ②コンテナの永続化
    volumes:
      - ./backend:/go/src/app
    ports:
      - 8080:8080

  flutter:
    build:
      context: .
      dockerfile: ./docker/flutter/Dockerfile
    volumes:
      - ./frontend:/frontend/src/app
    command: /bin/sh -c "while sleep 1000; do :; done"
    env_file:
      - flutter/.flutter.env
    #command: sh -c "yarn dev"
  webServer:
    image: nginx
    depends_on:
      - backend
    container_name: webServer
    ports:
      - 80:80
    environment:
      - TZ=Asia/Tokyo
    volumes:
      - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf
